### PR TITLE
Change colour scheme

### LINKED ISSUE #48: Use a better colour scheme for pollution concentration
Currently using colorcet `cc.coolwarm`, but is there one with purple in the middle of red and blue instead of white?

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
Closes #48 

@JimMadge what do you think about this colour scheme, I think it really emphasises that what's spreading is pollution!

I'm thinking it might be good as well to have a separate colour not part of the scheme for zero, so that uninfected nodes are clearly differentiated from those with a very low concentration, which isn't clear in this case

### CODE REVIEW

**Comment by JimMadge** [comment]
I think only using one colour instead of the transition between three (?) originally is much clearer. I do think the black is a bit harsh though given that mode nodes are generally going to have low pollution. Do you think it makes more sense to have zero as a fairly neutral colour, then make the colour more intense for high pollution (whether that's through saturation or brightness)?

I don't think we should give too much significance to zeroes. Otherwise the stark transition between zero and a very small pollution will be exaggerated.

**Comment by edwardchalstrey1** [comment]
> I think only using one colour instead of the transition between three (?) originally is much clearer. I do think the black is a bit harsh though given that mode nodes are generally going to have low pollution. Do you think it makes more sense to have zero as a fairly neutral colour, then make the colour more intense for high pollution (whether that's through saturation or brightness)?
> 
> I don't think we should give too much significance to zeroes. Otherwise the stark transition between zero and a very small pollution will be exaggerated.

I agree, the dark colours are quite hard to distinguish. I'll have a further play around with different styles and leave this PR open for now. Btw, this is the package I used to get the continuous colour scheme: https://colorcet.pyviz.org/user_guide/Continuous.html

**Comment by edwardchalstrey1** [comment]
> > I think only using one colour instead of the transition between three (?) originally is much clearer. I do think the black is a bit harsh though given that mode nodes are generally going to have low pollution. Do you think it makes more sense to have zero as a fairly neutral colour, then make the colour more intense for high pollution (whether that's through saturation or brightness)?
> > I don't think we should give too much significance to zeroes. Otherwise the stark transition between zero and a very small pollution will be exaggerated.
> 
> I agree, the dark colours are quite hard to distinguish. I'll have a further play around with different styles and leave this PR open for now. Btw, this is the package I used to get the continuous colour scheme: https://colorcet.pyviz.org/user_guide/Continuous.html

@JimMadge I think I've found one that works really nicely now! 
It distinguishes both the lower and upper pollution concentrations quite well I'd say

**Comment by JimMadge** [comment]
> > > I think only using one colour instead of the transition between three (?) originally is much clearer. I do think the black is a bit harsh though given that mode nodes are generally going to have low pollution. Do you think it makes more sense to have zero as a fairly neutral colour, then make the colour more intense for high pollution (whether that's through saturation or brightness)?
> > > I don't think we should give too much significance to zeroes. Otherwise the stark transition between zero and a very small pollution will be exaggerated.
> > 
> > 
> > I agree, the dark colours are quite hard to distinguish. I'll have a further play around with different styles and leave this PR open for now. Btw, this is the package I used to get the continuous colour scheme: https://colorcet.pyviz.org/user_guide/Continuous.html
> 
> @JimMadge I think I've found one that works really nicely now!
> It distinguishes both the lower and upper pollution concentrations quite well I'd say

@edwardchalstrey1 I think this one looks good. Should I merge this or are you still considering other options?

**Pull request merged**
