### PR TITLE
Add map toggle

### LINKED ISSUE #81: Find a solution to the map coordinates problem
Perhaps include an option to include or exclude maps based on whether node coordinates are map coordinates with a toggle button

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
Closes #81 

I've added a button that can be used to add or remove the map from the plot. By default, when the chosen network is ky2 (the default), the toggle is selected, but for the others, the map is turned off by default.

### CODE REVIEW

**Comment by JimMadge** [comment]
@edwardchalstrey1 I don't think the button really addresses the problem we were trying to solve. It doesn't make much sense to be able to show the map when we know the coordinate are incorrect and are unable to change them.

Could we instead have a coordinates file which gives enough information to scale the networkx coordinates to the web mercator coordinates? Something like 
``` yaml
x_offest: +137000
y_offest: -2570
x_scale: 0.95
y_scale: 1
```
These transformations can then be applied when the network is read, if present, and the graph will be rendered over a map. If the file is not present, just use the networkx coordinates.

**Comment by edwardchalstrey1** [comment]
> @edwardchalstrey1 I don't think the button really addresses the problem we were trying to solve. It doesn't make much sense to be able to show the map when we know the coordinate are incorrect and are unable to change them.
> 
> Could we instead have a coordinates file which gives enough information to scale the networkx coordinates to the web mercator coordinates? Something like
> 
> ```yaml
> x_offest: +137000
> y_offest: -2570
> x_scale: 0.95
> y_scale: 1
> ```
> 
> These transformations can then be applied when the network is read, if present, and the graph will be rendered over a map. If the file is not present, just use the networkx coordinates.

I had a think about this but I wasn't sure what benefit it would add (perhaps the same is true of the button). The offsets will apply to ky2 and not other examples (well ideally it would for these too, we just haven't found a nice place on the map for them), so not much different to just hardcoding the offsets in as we have already.

Plus, I'm thinking when we add the upload your own files feature, the guidelines should be, if you want an accurate map to display, make the node coordinates the actual lat/long. The map toggle then gives users the option to display or not display the map depending on whether that's the case.

**Comment by JimMadge** [comment]
> I had a think about this but I wasn't sure what benefit it would add (perhaps the same is true of the button). The offsets will apply to ky2 and not other examples (well ideally it would for these too, we just haven't found a nice place on the map for them), so not much different to just hardcoding the offsets in as we have already.

I think the important difference here is ky2 has an incorrect yet reasonable-looking location which we know the transformation for. If we hard code that transformation it renders the other networks in incorrect, unreasonable-looking locations. I think it those cases it is better to do away with the map and lat/lon coordinates altogether.

> Plus, I'm thinking when we add the upload your own files feature, the guidelines should be, if you want an accurate map to display, make the node coordinates the actual lat/long, rather than saying an offset file is required. The map toggle then gives users the option to display or not display the map depending on whether that's the case.

The problem with this is the graphs are generated in the app from WNTR models. The coordinates of the graph are out of the control of the user, and WNTR models (to my knowledge) have no sense of the global position of nodes, only their relative position.

In any case, we should only display a map and use lat/lon coordinates when we know how to project the network onto the map. So I don't think a toggle for the map is ever necessary, as this is determined by the input data and not the user.

**Comment by edwardchalstrey1** [comment]
> > I had a think about this but I wasn't sure what benefit it would add (perhaps the same is true of the button). The offsets will apply to ky2 and not other examples (well ideally it would for these too, we just haven't found a nice place on the map for them), so not much different to just hardcoding the offsets in as we have already.
> 
> I think the important difference here is ky2 has an incorrect yet reasonable-looking location which we know the transformation for. If we hard code that transformation it renders the other networks in incorrect, unreasonable-looking locations. I think it those cases it is better to do away with the map and lat/lon coordinates altogether.
> 
> > Plus, I'm thinking when we add the upload your own files feature, the guidelines should be, if you want an accurate map to display, make the node coordinates the actual lat/long, rather than saying an offset file is required. The map toggle then gives users the option to display or not display the map depending on whether that's the case.
> 
> The problem with this is the graphs are generated in the app from WNTR models. The coordinates of the graph are out of the control of the user, and WNTR models (to my knowledge) have no sense of the global position of nodes, only their relative position.
> 
> In any case, we should only display a map and use lat/lon coordinates when we know how to project the network onto the map. So I don't think a toggle for the map is ever necessary, as this is determined by the input data and not the user.

Ok fair enough, I think given you're probably right about WNTR I'm inclined to agree then

**Pull request closed without merging**
